App\AppBundle\Entity\Author:
    type: entity
    table: null
    repositoryClass: App\AppBundle\Entity\AuthorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        surname:
            type: string
            length: 255
        years:
            type: integer
        prueba:
            type: integer
    lifecycleCallbacks: {  }
