app_app_homepage:
    path:     /hello/{name}
    defaults: { _controller: AppAppBundle:Default:index }

recipes_id:
    path:     /recipes/{id}
    defaults: { _controller: AppAppBundle:Recipes:getbyid }
    requirements:
        id: \d+

recipes_create:
    path: /recipes/create
    defaults: { _controller: AppAppBundle:Recipes:create}

recipes_show:
    path: /recipes/show/{id}
    defaults: { _controller: AppAppBundle:Recipes:show}
    requirements:
        id: \d+
